import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&display=optional"
          rel="stylesheet"
        />

        <style>{`
          .material-symbols-outlined {
            font-variation-settings:
              'FILL' 0,
              'wght' 400,
              'GRAD' 0,
              'opsz' 48;
          }
        `}</style>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <Toaster />
        <Navbar />
        <div className="flex flex-col min-h-screen p-4">{children}</div>
        <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full items-center px-4 md:px-6 border-t">
          <p className="text-xs text-muted-foreground">
            &copy; 2025 CareerJunction. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
